'use strict';

/**
 * The locals contract every view receives.
 *
 *   site     — config, navigation, footer data, trust counters
 *   page     — title / description / canonical / robots / OG / JSON-LD
 *   helpers  — icon(), money and date formatting, WhatsApp links
 *
 * Routes never pass raw DB rows straight to a template: repository shapers own
 * that (§10). This file owns everything else.
 */

const fs = require('node:fs');
const path = require('node:path');
const config = require('../config');
const db = require('../db');
const { SORT_LABELS } = require('../db/listings');
const shape = require('../db/shape');
const blocks = require('../services/blocks');
const { icon, SERVICE_ICONS } = require('../services/icons');
const phone = require('./phone');
const { buildNav, megaMenuItems, whatsappLink } = require('../services/nav');
const seo = require('../services/seo');
const events = require('../services/events');

/** Cache of site-wide chrome data (services list, counters). */
let chromeCache = { at: 0, data: null };
const CHROME_TTL_MS = 60_000;

async function siteChrome() {
  if (chromeCache.data && Date.now() - chromeCache.at < CHROME_TTL_MS) return chromeCache.data;
  const [services, counters, cities] = await Promise.all([
    db.content.serviceSuite(),
    db.listings.networkCounters(),
    // FR-32: the markets we cover, in ops order with live counts — the header
    // switcher is on every page, static ones included, so this has to live in
    // the shared chrome rather than in one route.
    db.areas.cities(),
  ]);
  const data = { services, counters, cities };
  chromeCache = { at: Date.now(), data };
  return data;
}

/** Exposed for tests and after a rebuild. */
function invalidateChrome() {
  chromeCache = { at: 0, data: null };
}

const PHOTO_PATH = /^\/img\/(?:cars|details|site|blog|shop|hire)\/[\w-]+\.jpg$/;

/**
 * The 20px blur-up placeholder for a photo (§13.2), or null.
 *
 * Generated by scripts/prepare-images.js into image-blur.json and inlined as a
 * data URI, so the placeholder is already in the HTML when the first paint
 * happens — a placeholder fetched separately arrives after the photo it was
 * supposed to stand in for.
 */
function blurFor(url) {
  if (!url || !PHOTO_PATH.test(url)) return null;
  const manifest = require('./image-blur.json');
  return manifest[url] || null;
}

/** The 600×450 sibling — what a Save-Data visitor gets instead of the full file. */
function smallSrc(url) {
  return url && PHOTO_PATH.test(url) ? url.replace(/\.jpg$/, '-600.jpg') : null;
}

/**
 * Every prepared photo has a 600×450 `-600` sibling (scripts/prepare-images.js).
 * Returns a srcset so cards and galleries stop shipping the 1200px file to a
 * phone, or null when the media is a placeholder/dealer URL we cannot resize —
 * and null under Save-Data, where the `src` is already the small file and a
 * srcset would only invite the browser to fetch a bigger one (§13.2).
 */
function srcsetFor(url, { saveData = false } = {}) {
  if (saveData || !url || !PHOTO_PATH.test(url)) return null;
  return `${url.replace(/\.jpg$/, '-600.jpg')} 600w, ${url} 1200w`;
}

let videoManifest = null;

/**
 * What a clip costs, before anything plays (§13.2).
 *
 * Measured by scripts/generate-videos.js and read from the manifest, so the
 * "0:12 · 238 KB" under a play button is a fact about the file rather than a
 * number someone typed — a label that overstates the cost is as dishonest as one
 * that hides it.
 */
function videoFor(src) {
  if (!src) return null;
  if (!videoManifest) videoManifest = require('./video-manifest.json');
  return videoManifest[src] || null;
}

/** Seconds → "0:12" / "1:05". */
function formatDuration(seconds) {
  const total = Math.max(0, Math.round(Number(seconds) || 0));
  return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, '0')}`;
}

/** Bytes → "238 KB" / "1.2 MB". Decimal units: this is what a data plan counts. */
function formatBytes(bytes) {
  const value = Number(bytes) || 0;
  if (value < 1000) return `${value} B`;
  if (value < 1_000_000) return `${Math.round(value / 1000)} KB`;
  return `${(value / 1_000_000).toFixed(1)} MB`;
}

/**
 * The `src` for a photo: the small file when the visitor asked us to spend less
 * data, the full file otherwise.
 */
function photoSrc(url, { saveData = false } = {}) {
  if (!saveData) return url;
  return smallSrc(url) || url;
}

/**
 * The company's own mark, when one has been generated from `assets/brand/`.
 *
 * `scripts/generate-icons.js` writes `public/img/logo.png` only when there is a
 * master to cut it from, so this file check is the whole switch: with a mark,
 * the header, the drawer and the console draw it; without one they draw the
 * inline shield they have always drawn. No template has to know which is in
 * force, and nothing ever points at a file that is not there.
 */
const BRAND_MARK = path.join(__dirname, '..', '..', 'public', 'img', 'logo.png');
const BRAND_MARK_URL = '/img/logo.png';

function brandMark() {
  return fs.existsSync(BRAND_MARK) ? BRAND_MARK_URL : null;
}

function helpers({ saveData = false } = {}) {
  return {
    saveData,
    srcsetFor: (url) => srcsetFor(url, { saveData }),
    photoSrc: (url) => photoSrc(url, { saveData }),
    blurFor,
    smallSrc,
    videoFor,
    formatDuration,
    formatBytes,
    icon,
    SERVICE_ICONS,
    brandMark: brandMark(),
    whatsappLink,
    inlineText: blocks.inline,
    phonePretty: phone.pretty,
    formatNaira: shape.formatNaira,
    formatNairaCompact: shape.formatNairaCompact,
    formatMileage: shape.formatMileage,
    relativeDays: shape.relativeDays,
    koboToNaira: shape.koboToNaira,
    GRADE_LABELS: shape.GRADE_LABELS,
    GRADE_TOOLTIPS: shape.GRADE_TOOLTIPS,
    CONDITION_LABELS: shape.CONDITION_LABELS,
    BODY_TYPE_LABELS: shape.BODY_TYPE_LABELS,
    TRANSMISSION_LABELS: shape.TRANSMISSION_LABELS,
    FUEL_LABELS: shape.FUEL_LABELS,
    PRICE_POSITION: shape.PRICE_POSITION,
    absolute: seo.absolute,
    esc: seo.esc,
    jsonLdScript: seo.jsonLdScript,
    eventNames: events.EVENT_NAMES,
    localBusinessSchema: seo.localBusinessSchema,
    webSiteSchema: seo.webSiteSchema,
    faqSchema: seo.faqSchema,
    breadcrumbSchema: seo.breadcrumbSchema,
    itemListSchema: seo.itemListSchema,
    SORT_LABELS: SORT_LABELS,
    vdpPath: seo.vdpPath,
    vdpMeta: seo.vdpMeta,
    serviceMeta: seo.serviceMeta,
  };
}

/**
 * Build the locals object for a page render.
 *
 * @param {string} routePath  current request path — drives aria-current and nav
 * @param {object} page       page meta (see defaultPage)
 * @param {object} extra      view-specific data
 */
async function buildLocals(routePath, page = {}, extra = {}) {
  const chrome = await siteChrome();
  const nav = buildNav(routePath);
  // §13.2: the `Save-Data: on` request header, threaded through so every view
  // can render the lighter variant without each route remembering to ask.
  const saveData = Boolean(extra.saveData);
  return {
    site: {
      config,
      url: config.siteUrl,
      business: config.business,
      soldArchive: config.soldArchive,
      nav,
      services: chrome.services,
      megaMenu: megaMenuItems(chrome.services),
      counters: chrome.counters,
      cities: chrome.cities,
      // The market this particular page is about, when the route knows one
      // (a city facet, or /cars filtered to a market). Null means “the whole
      // network”, and the client fills the label from the visitor's cookie.
      city: extra.serviceCity || null,
      analytics: config.analytics,
      currentPath: routePath,
      saveData,
    },
    page: defaultPage(page),
    helpers: helpers({ saveData }),
    ...extra,
  };
}

const BASE_DESCRIPTION =
  'Verified cars from trusted Port Harcourt lots — inspections, documents and negotiation handled for you. Every vehicle verified. Every price compared. Every deal honest.';

const TITLE_SUFFIX = ' | HonestCars';
const TITLE_BUDGET = 64; // §14.2 keeps titles inside the SERP line
const DESCRIPTION_BUDGET = 158;

function defaultPage(page = {}) {
  const raw = page.title || 'Cars for sale in Port Harcourt';
  // Hard ceiling as a safety net: no route can push a title past the SERP
  // width even if someone writes long copy into a CMS row.
  const base = page.titleSuffix === false ? seo.truncate(raw, TITLE_BUDGET) : seo.truncate(raw, TITLE_BUDGET - TITLE_SUFFIX.length);
  return {
    title: page.titleSuffix === false ? base : `${base}${TITLE_SUFFIX}`,
    metaTitle: base,
    description: seo.truncate(page.description || BASE_DESCRIPTION, DESCRIPTION_BUDGET),
    canonical: seo.absolute(page.canonical || '/'),
    robots: page.robots || 'index,follow',
    og: {
      type: page.ogType || 'website',
      image: seo.absolute(page.ogImage || '/og/default.png'),
      imageAlt: page.ogImageAlt || base,
      imageWidth: 1200,
      imageHeight: 630,
    },
    jsonLd: page.jsonLd || [],
    bodyClass: page.bodyClass || '',
    layout: page.layout || 'base',
    breadcrumbs: page.breadcrumbs || null,
    activeNav: page.activeNav || null,
  };
}

module.exports = { buildLocals, siteChrome, invalidateChrome, helpers, defaultPage, srcsetFor, blurFor, smallSrc, photoSrc, videoFor, formatDuration, formatBytes, BASE_DESCRIPTION };
